# Generated by Django 4.2.3 on 2024-02-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatlog',
            fields=[
                ('chatlognr', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.TextField()),
                ('username', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
